-- ═══════════════════════════════════════════════════════════
-- 02_seed_reference.sql — INTENTIONALLY EMPTY
-- ═══════════════════════════════════════════════════════════
-- No initial seed data for this entity.
-- All exclusion rules are created by admin user input.
--
-- sap_document_number_ref is populated by the SAP sync pipeline,
-- not by this skill.
-- ═══════════════════════════════════════════════════════════
